# Generated by Django 3.0.6 on 2020-05-05 15:01

from django.db import migrations
import django_extensions.db.fields
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AlterField(
            model_name='image',
            name='raw_image',
            field=versatileimagefield.fields.VersatileImageField(height_field='height', upload_to='image_data/', verbose_name='Raw Image', width_field='width'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uuid',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
